### ISSUE TITLE
API Key Input Crash/Failure to save 

### ISSUE THREAD

**Issue by MKme** [flagshipcompany/flagship-for-woocommerce-bedrock#30]
Setup in woocommerce went fine. Plugin working but input of API token is a crash to this every time:  

here has been a critical error on this website. Please check your site admin email inbox for instructions.

Cannot enter the token. Tried multiple timers.  The rest of the settings save fine- it is the token that fails it.  Perhaps your datatype is wrong or not enough chars for the current length string?

**Comment by MKme** [comment]
Current setup:  
![wpsetup](https://user-images.githubusercontent.com/13653062/214060025-b921f78e-75a9-41df-ac45-933614edd7a3.JPG)
Clears the api when you hit back from the error.  
If you hit save you get success with API = blank 
![success](https://user-images.githubusercontent.com/13653062/214060485-6e4001d9-7ea7-4f19-9f65-b94118aa4580.JPG)

**Comment by MKme** [comment]
Error details:

An error of type E_ERROR was caused in line 17 of the file D:\Inetpub\vhosts\redacted\wp-content\plugins\flagship-for-woocommerce-bedrock-1.0.20\includes\Requests\Validate_Token_Request.php. Error message: Uncaught Error: Class 'Flagship\Shipping\Flagship' not found in D:\Inetpub\vhosts\redacted\wp-content\plugins\flagship-for-woocommerce-bedrock-1.0.20\includes\Requests\Validate_Token_Request.php:17
Stack trace:
#0 D:\Inetpub\vhosts\redacted\wp-content\plugins\flagship-for-woocommerce-bedrock-1.0.20\includes\Helpers\Validation_Helper.php(27): FlagshipWoocommerceBedrock\Requests\Validate_Token_Request->validateToken()
#1 D:\Inetpub\vhosts\redacted\wp-content\plugins\flagship-for-woocommerce-bedrock-1.0.20\includes\WC_Flagship_Shipping_Method.php(107): FlagshipWoocommerceBedrock\Helpers\Validation_Helper->validateToken()
#2 D:\Inetpub\vhosts\redacted\wp-includes\class-wp-hook.php(308): FlagshipWoocommerceBedrock\WC_Flagship_Shipping_Method->validate_admin_options()
#3 D:\Inetpub\vhosts\redacted\wp-includes\plugin.php(205): WP_Hook->apply_filters()
#4 D:\Inetpub\vhosts\redacted\wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-settings-api.php(223): apply_filters()

**Comment by radua** [comment]
Hello @MKme , which version of woocommerce and php are you using?
Can you please send your token to developers@flagshipcompany.com

**Comment by MKme** [comment]
I did a bit better I think.  Here you are  https://github.com/flagshipcompany/flagship-for-woocommerce-bedrock/issues/30
[https://opengraph.githubassets.com/eed2066b6128a087df8f0057782b52a4dde4148b6c5531608bae4858ff8102f4/flagshipcompany/flagship-for-woocommerce-bedrock/issues/30]<https://github.com/flagshipcompany/flagship-for-woocommerce-bedrock/issues/30>
API Key Input Crash/Failure to save · Issue #30 · flagshipcompany/flagship-for-woocommerce-bedrock<https://github.com/flagshipcompany/flagship-for-woocommerce-bedrock/issues/30>
Setup in woocommerce went fine. Plugin working but input of API token is a crash to this every time: here has been a critical error on this website. Please check your site admin email inbox for ins...
github.com

________________________________

**Comment by MKme** [comment]
Emailed API

**Comment by MKme** [comment]
PHP  On (version: 7.3.25;

**Comment by MKme** [comment]
PHP upgrade to 8.1 allows it to accept the token provided by your dev.
